const ERROR_CODES = {
  // Authentication
  UNAUTHORIZED: "UNAUTHORIZED",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",

  // Validation
  VALIDATION_ERROR: "VALIDATION_ERROR",

  // Application
  APPLICATION_NOT_FOUND: "APPLICATION_NOT_FOUND",

  // Note
  NOTE_NOT_FOUND: "NOTE_NOT_FOUND",

  // Document
  DOCUMENT_NOT_FOUND: "DOCUMENT_NOT_FOUND",
  INVALID_FILE_TYPE: "INVALID_FILE_TYPE",

  // Resume Analysis
  RESUME_ANALYSIS_NOT_FOUND: "RESUME_ANALYSIS_NOT_FOUND",
  RESUME_ANALYSIS_RATE_LIMITED: "RESUME_ANALYSIS_RATE_LIMITED",
  JOB_DESCRIPTION_MISSING: "JOB_DESCRIPTION_MISSING",
  RESUME_NOT_FOUND: "RESUME_NOT_FOUND",
  ANALYSIS_ALREADY_PROCESSING: "ANALYSIS_ALREADY_PROCESSING",

  // AI Errors
  AI_ANALYSIS_FAILED: "AI_ANALYSIS_FAILED",
  AI_ANALYSIS_EMPTY_RESPONSE: "AI_ANALYSIS_EMPTY_RESPONSE",
  AI_ANALYSIS_INVALID_RESPONSE: "AI_ANALYSIS_INVALID_RESPONSE",
  AI_ANALYSIS_VALIDATION_FAILED: "AI_ANALYSIS_VALIDATION_FAILED",

  // General
  INTERNAL_ERROR: "INTERNAL_ERROR",
};

export default ERROR_CODES;
