const ERROR_CODES = {
  // Authentication
  UNAUTHORIZED: "UNAUTHORIZED",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",

  // Validation
  VALIDATION_ERROR: "VALIDATION_ERROR",

  // Application
  APPLICATION_NOT_FOUND: "APPLICATION_NOT_FOUND",

  // Note
  NOTE_NOT_FOUND: "NOTE_NOT_FOUND",

  // Document
  DOCUMENT_NOT_FOUND: "DOCUMENT_NOT_FOUND",
  INVALID_FILE_TYPE: "INVALID_FILE_TYPE",

  // General
  INTERNAL_ERROR: "INTERNAL_ERROR",
};

export default ERROR_CODES;
